version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp
      POSTGRES_USER: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "alembic upgrade head && python -m mcp_multiagent_selector.mcp_server.server"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app/src

volumes:
  pgdata: 